### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by nileshpatra** [nileshpatra/Org-manage-bot#8]
I prefer the GNU GPLv2. Make a PR to add that in

**Comment by ArdeshirV** [comment]
OK!

**Comment by nileshpatra** [comment]
Hey @ArdeshirV ! Thanks for the PR. LGTM, merging. You are also welcome to join the telegram channel [here](https://t.me/joinchat/J22LWxGkZTvt2bSEZ7wAPg) for any further discussion.
